export const TOGGLE_FLASH_MESSAGE = 'TOGGLE_FLASH_MESSAGE';

export const ADD_RECORD = 'ADD_RECORD';
export const SET_RECORDS = 'SET_RECORDS';
export const GET_RECORD_FROM_CACHE = 'GET_RECORD_FROM_CACHE';
export const REMOVE_RECORD = 'REMOVE_RECORD';
export const SET_IS_PLAYING = 'SET_IS_PLAYING';
